packages:
  - packages/*
  - packages/plugin/*

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  preact@>=10.27.0 <10.27.3: '>=10.27.3'
  tar@<=7.5.2: '>=7.5.3'
  tmp@<=0.2.3: '>=0.2.4'
  vite@>=5.2.6 <=5.4.20: '>=5.4.21'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
